spring:
  datasource:
    url: jdbc:postgresql://dpg-cud0amogph6c738jjne0-a.frankfurt-postgres.render.com:5432/ordermanagementpostgresql
    username: jelena
    password: KTwvMxHsh8XJ1d1NEsIb7Rak8elc2o1Z
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always 

logging:
  level:
    org.springframework.jdbc.core: DEBUG
  file:
    name: logs/application.log
